### ISSUE TITLE
Incorrect error for SRV "record name must not be empty"

### ISSUE THREAD

**Issue by pawel-kow** [Domain-Connect/dc-template-linter#1]
See output for justhost.com.hosting_and_email.json
```json
{"level":"error","template":"justhost.com.hosting_and_email.json","record":15,"type":"SRV","time":1708274108,"message":"record name must not be empty"}
```
The said record:
```json
    {
      "target": "emaildiscovery.cpanel.net",
      "type": "SRV",
      "service": "_autodiscover",
      "protocol": "_tcp",
      "name": "",
      "essential": "OnApply",
      "ttl": 14400,
      "priority": 0,
      "weight": 0,
      "port": 443
    },
```

As per spec 5.3 this is a correct record:
> The name for the SRV record.
> This value is relative to the applied host and domain. **A value of empty or @ indicates the root of the applied host and domain.**
> This value should not contain variables unless absolutely necessary. This is discussed below.

**Comment by kerolasa** [comment]
Thank you for reporting. That was clearly a bug in this linter. Fixed in 802a87462a187f56d40b5e226eedade1e0011043.
