### ISSUE TITLE
Check for invalid (static) hostnames

### ISSUE THREAD

**Issue by pawel-kow** [Domain-Connect/dc-template-linter#13]
See this commit: https://github.com/Domain-Connect/Templates/pull/568/commits/d29e426a9f6c9c5bc6764f0d8327dd6b7e4d945f

There is a host       `"host": "secureserver_s2._domainkey",` which is actually an invalid DNS label

**Comment by kerolasa** [comment]
I added a bit code to catch static names with underscores.

With that in place it is starting to feel like I should consider adding a test suite to ensure various checks do not break as the code accumulates. Perhaps I'll get to do that one day.
