### ISSUE TITLE
Detect invalid variable references

### ISSUE THREAD

**Issue by pawel-kow** [Domain-Connect/dc-template-linter#7]
It would be a nice feature to detect broken variable references, like the one below
```
      {
         "type":"A",
         "host":"@",
         "pointsTo":"%IP",
         "ttl":3600
      }
```

- any uneven occurance of `%` character in a text field that can contain variable
- if anything other than `[a-zA-Z]` characters is between two consecutive `%` characters

**Comment by kerolasa** [comment]
Checking template variables is great idea.  Proposed valid characters did
not appear to match with what  Templates repository is already using.  I had
to add `[0-9]` and `_` (underscore) and `-` (hyphen) to the list.  These do
not seem overly controversial additions, and the good news is it will be
easy to catch truly problematic characters sneaking into templates.
